// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// BarOneChild is an object representing the database table.
type BarOneChild struct {
	ID    int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name  null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	BarID int         `boil:"bar_id" json:"bar_id" toml:"bar_id" yaml:"bar_id"`

	R *barOneChildR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L barOneChildL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BarOneChildColumns = struct {
	ID    string
	Name  string
	BarID string
}{
	ID:    "id",
	Name:  "name",
	BarID: "bar_id",
}

// BarOneChildRels is where relationship names are stored.
var BarOneChildRels = struct {
	Bar string
}{
	Bar: "Bar",
}

// barOneChildR is where relationships are stored.
type barOneChildR struct {
	Bar *Bar
}

// NewStruct creates a new relationship struct
func (*barOneChildR) NewStruct() *barOneChildR {
	return &barOneChildR{}
}

// barOneChildL is where Load methods for each relationship are stored.
type barOneChildL struct{}

var (
	barOneChildColumns               = []string{"id", "name", "bar_id"}
	barOneChildColumnsWithoutDefault = []string{"name", "bar_id"}
	barOneChildColumnsWithDefault    = []string{"id"}
	barOneChildPrimaryKeyColumns     = []string{"id"}
)

type (
	// BarOneChildSlice is an alias for a slice of pointers to BarOneChild.
	// This should generally be used opposed to []BarOneChild.
	BarOneChildSlice []*BarOneChild
	// BarOneChildHook is the signature for custom BarOneChild hook methods
	BarOneChildHook func(context.Context, boil.ContextExecutor, *BarOneChild) error

	barOneChildQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	barOneChildType                 = reflect.TypeOf(&BarOneChild{})
	barOneChildMapping              = queries.MakeStructMapping(barOneChildType)
	barOneChildPrimaryKeyMapping, _ = queries.BindMapping(barOneChildType, barOneChildMapping, barOneChildPrimaryKeyColumns)
	barOneChildInsertCacheMut       sync.RWMutex
	barOneChildInsertCache          = make(map[string]insertCache)
	barOneChildUpdateCacheMut       sync.RWMutex
	barOneChildUpdateCache          = make(map[string]updateCache)
	barOneChildUpsertCacheMut       sync.RWMutex
	barOneChildUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
)

var barOneChildBeforeInsertHooks []BarOneChildHook
var barOneChildBeforeUpdateHooks []BarOneChildHook
var barOneChildBeforeDeleteHooks []BarOneChildHook
var barOneChildBeforeUpsertHooks []BarOneChildHook

var barOneChildAfterInsertHooks []BarOneChildHook
var barOneChildAfterSelectHooks []BarOneChildHook
var barOneChildAfterUpdateHooks []BarOneChildHook
var barOneChildAfterDeleteHooks []BarOneChildHook
var barOneChildAfterUpsertHooks []BarOneChildHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *BarOneChild) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range barOneChildBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *BarOneChild) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range barOneChildBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *BarOneChild) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range barOneChildBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *BarOneChild) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range barOneChildBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *BarOneChild) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range barOneChildAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *BarOneChild) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range barOneChildAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *BarOneChild) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range barOneChildAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *BarOneChild) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range barOneChildAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *BarOneChild) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range barOneChildAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBarOneChildHook registers your hook function for all future operations.
func AddBarOneChildHook(hookPoint boil.HookPoint, barOneChildHook BarOneChildHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		barOneChildBeforeInsertHooks = append(barOneChildBeforeInsertHooks, barOneChildHook)
	case boil.BeforeUpdateHook:
		barOneChildBeforeUpdateHooks = append(barOneChildBeforeUpdateHooks, barOneChildHook)
	case boil.BeforeDeleteHook:
		barOneChildBeforeDeleteHooks = append(barOneChildBeforeDeleteHooks, barOneChildHook)
	case boil.BeforeUpsertHook:
		barOneChildBeforeUpsertHooks = append(barOneChildBeforeUpsertHooks, barOneChildHook)
	case boil.AfterInsertHook:
		barOneChildAfterInsertHooks = append(barOneChildAfterInsertHooks, barOneChildHook)
	case boil.AfterSelectHook:
		barOneChildAfterSelectHooks = append(barOneChildAfterSelectHooks, barOneChildHook)
	case boil.AfterUpdateHook:
		barOneChildAfterUpdateHooks = append(barOneChildAfterUpdateHooks, barOneChildHook)
	case boil.AfterDeleteHook:
		barOneChildAfterDeleteHooks = append(barOneChildAfterDeleteHooks, barOneChildHook)
	case boil.AfterUpsertHook:
		barOneChildAfterUpsertHooks = append(barOneChildAfterUpsertHooks, barOneChildHook)
	}
}

// One returns a single barOneChild record from the query.
func (q barOneChildQuery) One(ctx context.Context, exec boil.ContextExecutor) (*BarOneChild, error) {
	o := &BarOneChild{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for bar_one_child")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all BarOneChild records from the query.
func (q barOneChildQuery) All(ctx context.Context, exec boil.ContextExecutor) (BarOneChildSlice, error) {
	var o []*BarOneChild

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to BarOneChild slice")
	}

	if len(barOneChildAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all BarOneChild records in the query.
func (q barOneChildQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count bar_one_child rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q barOneChildQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if bar_one_child exists")
	}

	return count > 0, nil
}

// Bar pointed to by the foreign key.
func (o *BarOneChild) Bar(mods ...qm.QueryMod) barQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.BarID),
	}

	queryMods = append(queryMods, mods...)

	query := Bars(queryMods...)
	queries.SetFrom(query.Query, "`bar`")

	return query
}

// LoadBar allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (barOneChildL) LoadBar(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBarOneChild interface{}, mods queries.Applicator) error {
	var slice []*BarOneChild
	var object *BarOneChild

	if singular {
		object = maybeBarOneChild.(*BarOneChild)
	} else {
		slice = *maybeBarOneChild.(*[]*BarOneChild)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &barOneChildR{}
		}
		args = append(args, object.BarID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &barOneChildR{}
			}

			for _, a := range args {
				if a == obj.BarID {
					continue Outer
				}
			}

			args = append(args, obj.BarID)

		}
	}

	query := NewQuery(qm.From(`bar`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Bar")
	}

	var resultSlice []*Bar
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Bar")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for bar")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for bar")
	}

	if len(barOneChildAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Bar = foreign
		if foreign.R == nil {
			foreign.R = &barR{}
		}
		foreign.R.BarOneChildren = append(foreign.R.BarOneChildren, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.BarID == foreign.ID {
				local.R.Bar = foreign
				if foreign.R == nil {
					foreign.R = &barR{}
				}
				foreign.R.BarOneChildren = append(foreign.R.BarOneChildren, local)
				break
			}
		}
	}

	return nil
}

// SetBar of the barOneChild to the related item.
// Sets o.R.Bar to related.
// Adds o to related.R.BarOneChildren.
func (o *BarOneChild) SetBar(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Bar) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `bar_one_child` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"bar_id"}),
		strmangle.WhereClause("`", "`", 0, barOneChildPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.BarID = related.ID
	if o.R == nil {
		o.R = &barOneChildR{
			Bar: related,
		}
	} else {
		o.R.Bar = related
	}

	if related.R == nil {
		related.R = &barR{
			BarOneChildren: BarOneChildSlice{o},
		}
	} else {
		related.R.BarOneChildren = append(related.R.BarOneChildren, o)
	}

	return nil
}

// BarOneChildren retrieves all the records using an executor.
func BarOneChildren(mods ...qm.QueryMod) barOneChildQuery {
	mods = append(mods, qm.From("`bar_one_child`"))
	return barOneChildQuery{NewQuery(mods...)}
}

// FindBarOneChild retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBarOneChild(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*BarOneChild, error) {
	barOneChildObj := &BarOneChild{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `bar_one_child` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, barOneChildObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from bar_one_child")
	}

	return barOneChildObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *BarOneChild) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no bar_one_child provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(barOneChildColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	barOneChildInsertCacheMut.RLock()
	cache, cached := barOneChildInsertCache[key]
	barOneChildInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			barOneChildColumns,
			barOneChildColumnsWithDefault,
			barOneChildColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(barOneChildType, barOneChildMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(barOneChildType, barOneChildMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `bar_one_child` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `bar_one_child` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `bar_one_child` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, barOneChildPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into bar_one_child")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == barOneChildMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for bar_one_child")
	}

CacheNoHooks:
	if !cached {
		barOneChildInsertCacheMut.Lock()
		barOneChildInsertCache[key] = cache
		barOneChildInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the BarOneChild.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *BarOneChild) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	barOneChildUpdateCacheMut.RLock()
	cache, cached := barOneChildUpdateCache[key]
	barOneChildUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			barOneChildColumns,
			barOneChildPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update bar_one_child, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `bar_one_child` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, barOneChildPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(barOneChildType, barOneChildMapping, append(wl, barOneChildPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update bar_one_child row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for bar_one_child")
	}

	if !cached {
		barOneChildUpdateCacheMut.Lock()
		barOneChildUpdateCache[key] = cache
		barOneChildUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q barOneChildQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for bar_one_child")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for bar_one_child")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BarOneChildSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), barOneChildPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `bar_one_child` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, barOneChildPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in barOneChild slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all barOneChild")
	}
	return rowsAff, nil
}

var mySQLBarOneChildUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *BarOneChild) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no bar_one_child provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(barOneChildColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLBarOneChildUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	barOneChildUpsertCacheMut.RLock()
	cache, cached := barOneChildUpsertCache[key]
	barOneChildUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			barOneChildColumns,
			barOneChildColumnsWithDefault,
			barOneChildColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			barOneChildColumns,
			barOneChildPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert bar_one_child, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "bar_one_child", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `bar_one_child` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(barOneChildType, barOneChildMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(barOneChildType, barOneChildMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for bar_one_child")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == barOneChildMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(barOneChildType, barOneChildMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for bar_one_child")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for bar_one_child")
	}

CacheNoHooks:
	if !cached {
		barOneChildUpsertCacheMut.Lock()
		barOneChildUpsertCache[key] = cache
		barOneChildUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single BarOneChild record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BarOneChild) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no BarOneChild provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), barOneChildPrimaryKeyMapping)
	sql := "DELETE FROM `bar_one_child` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from bar_one_child")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for bar_one_child")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q barOneChildQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no barOneChildQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from bar_one_child")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for bar_one_child")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BarOneChildSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no BarOneChild slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(barOneChildBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), barOneChildPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `bar_one_child` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, barOneChildPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from barOneChild slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for bar_one_child")
	}

	if len(barOneChildAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BarOneChild) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBarOneChild(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BarOneChildSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BarOneChildSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), barOneChildPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `bar_one_child`.* FROM `bar_one_child` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, barOneChildPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BarOneChildSlice")
	}

	*o = slice

	return nil
}

// BarOneChildExists checks if the BarOneChild row exists.
func BarOneChildExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `bar_one_child` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if bar_one_child exists")
	}

	return exists, nil
}
