// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Bar         string
	BarChild    string
	BarOneChild string
	Foo         string
	FooChild    string
}{
	Bar:         "bar",
	BarChild:    "bar_child",
	BarOneChild: "bar_one_child",
	Foo:         "foo",
	FooChild:    "foo_child",
}
