// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Bars", testBarsUpsert)

	t.Run("BarChildren", testBarChildrenUpsert)

	t.Run("BarOneChildren", testBarOneChildrenUpsert)

	t.Run("Foos", testFoosUpsert)

	t.Run("FooChildren", testFooChildrenUpsert)
}
