// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/ryutah/go-sample-codes/wire/simple/foo"
)

// Injectors from inject.go:

func initializeBaz(ctx context.Context) (foo.Baz, error) {
	fooFoo := foo.ProvideFoo()
	bar := foo.ProvideBar(fooFoo)
	baz, err := foo.ProvideBaz(ctx, bar)
	if err != nil {
		return foo.Baz{}, err
	}
	return baz, nil
}
