version: "3"
services:
  db:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foo
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data:
